"""Test data and reference examples for policy assessment."""

from .assessment_examples import (
    POLICY_EXTRACT_ABN, POLICY_PAGES_ABN, ASSESSMENT_ABN,
    POLICY_EXTRACT_HSBC, POLICY_PAGES_HSBC, ASSESSMENT_HSBC,
    POLICY_EXTRACT_BBVA, POLICY_PAGES_BBVA, ASSESSMENT_BBVA,
    POLICY_EXTRACT_BARCLAYS, POLICY_PAGES_BARCLAYS, ASSESSMENT_BARCLAYS
)

__all__ = [
    'POLICY_EXTRACT_ABN', 'POLICY_PAGES_ABN', 'ASSESSMENT_ABN',
    'POLICY_EXTRACT_HSBC', 'POLICY_PAGES_HSBC', 'ASSESSMENT_HSBC',
    'POLICY_EXTRACT_BBVA', 'POLICY_PAGES_BBVA', 'ASSESSMENT_BBVA',
    'POLICY_EXTRACT_BARCLAYS', 'POLICY_PAGES_BARCLAYS', 'ASSESSMENT_BARCLAYS'
]
